# Generated by Django 6.0.2 on 2026-02-12 15:37

import catalog.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Наименование')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL', max_length=250, unique=True, verbose_name='Slug')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('image_original', models.ImageField(blank=True, null=True, upload_to=catalog.models.product_image_path, verbose_name='Оригинальное изображение')),
                ('image_large', models.ImageField(blank=True, editable=False, null=True, upload_to=catalog.models.product_image_path, verbose_name='Большое изображение (800x800)')),
                ('image_medium', models.ImageField(blank=True, editable=False, null=True, upload_to=catalog.models.product_image_path, verbose_name='Среднее изображение (400x400)')),
                ('image_small', models.ImageField(blank=True, editable=False, null=True, upload_to=catalog.models.product_image_path, verbose_name='Маленькое изображение (200x200)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.subcategory', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
